

from pytorch_lightning import Trainer
from pytorch_lightning.loggers import WandbLogger
from trainer_ASV import SpeechLLMLightning
from dataset_ASV import InstructionalAudioDataset, MyCollator, InstructionalNumpyDataset
from pytorch_lightning.strategies import DDPStrategy
from pytorch_lightning.callbacks import TQDMProgressBar

import torch.utils.data as data_utils
from pytorch_lightning.callbacks import ModelCheckpoint, EarlyStopping
import wandb
import argparse
import os

import torch
from utils import get_model_config

if __name__ == "__main__":
    model_config = get_model_config()
    
    wandb.init(project="speechllm", name=model_config['log_path'], group=model_config['group'])
    logger = WandbLogger(project="speechllm", name=model_config['log_path'], group=model_config['group'])

    print(model_config)

    model = SpeechLLMLightning(**model_config)
    print("SpeechLLMLightning loaded")
    
    tokenizer = model.llm_tokenizer

    print("Model loaded")

    data_name = list(model_config['train_sets'].keys())[0]
    print(f"Using dataset {data_name} only")
    if 'precomputed' in model_config['audio_encoder_name']:
        train_dataset = InstructionalNumpyDataset(
            csv_file=f'./data/{data_name}.csv',
            mode='train'
            )
    else:
        train_dataset = InstructionalAudioDataset(
            csv_file=f'./data/{data_name}.csv',
            mode='train', 
            max_len=60
            )

    data_name = list(model_config['dev_sets'].keys())[0]
    if 'precomputed' in model_config['audio_encoder_name']:
        val_dataset = InstructionalNumpyDataset(
            csv_file=f'./data/{data_name}.csv',
            mode='test'
            )
    else:
        val_dataset = InstructionalAudioDataset(
            csv_file = f'./data/{data_name}.csv',
            mode='test',
            max_len=60
            )

    print(f"Train set:{len(train_dataset)}, val set:{len(val_dataset)}, batch size:{model_config['batch_size']}")
    num_workers=4 #put to 0 for debugging
    my_collator = MyCollator(model_config['audio_encoder_name'], tokenizer)
    # sampler = data_utils.WeightedRandomSampler(train_dataset.datasets_weights, num_samples=len(train_dataset.datasets_weights), replacement=True)
    # Check whether it is generated by Composite / ConcatDataset
    shuffle = True  # If sampler is used, shuffle must be False
    train_loader = data_utils.DataLoader(
                        train_dataset, 
                        batch_size=model_config['batch_size'], 
                        shuffle=shuffle, 
                        collate_fn=my_collator, 
                        num_workers=num_workers,
                        persistent_workers=False, pin_memory=False, prefetch_factor=None) #for debugging segmentation fault
    val_loader = data_utils.DataLoader(
                        val_dataset, 
                        batch_size=model_config['batch_size'], 
                        shuffle=False, 
                        collate_fn=my_collator, 
                        num_workers=num_workers,
                        persistent_workers=False, pin_memory=False, prefetch_factor=None) #for debugging segmentation fault

    
    checkpoint_callback = ModelCheckpoint(
                    dirpath=f"checkpoints/{model_config['group']}/{model_config['model_name']}", 
                    filename=model_config['model_name']+'epoch-{epoch}', 
                    save_top_k=3, 
                    monitor="val/EER", 
                    save_last=True,
                    every_n_epochs=2)
    early_stop_callback = EarlyStopping(monitor="val/loss", min_delta=0.00, patience=10, verbose=False, mode="min")


    trainer = Trainer(
            max_epochs=model_config['total_training_epoch'], 
            devices=1, accelerator="gpu", 
            strategy=DDPStrategy(find_unused_parameters=True),#model_config['finetune_encoder']
            limit_train_batches=1000, 
            limit_val_batches=20,
            log_every_n_steps=100, 
            enable_checkpointing=True, 
            enable_progress_bar=True,
            callbacks=[checkpoint_callback, TQDMProgressBar(refresh_rate=100*model_config['grad_accumulate_steps'])],
            fast_dev_run=False, logger=logger, 
            accumulate_grad_batches=model_config['grad_accumulate_steps']
    )
    trainer.fit(model, train_loader, val_loader)

